name: Terraform Enterprise Pipeline

#--------------------------------------------------
# Trigger Events
#--------------------------------------------------
on:
  push:
    branches:
      - develop
      - main

  pull_request:
    branches:
      - develop
      - main

  workflow_dispatch:

#--------------------------------------------------
# Global Environment Variables
#--------------------------------------------------
env:
  TF_VERSION: "1.13.4"
  WORKING_DIR: "./terraform"

#--------------------------------------------------
# Required Permissions (OIDC)
#--------------------------------------------------
permissions:
  id-token: write
  contents: read
  pull-requests: write

#--------------------------------------------------
# Prevent multiple deployments
#--------------------------------------------------
concurrency:
  group: terraform-${{ github.ref }}
  cancel-in-progress: true

###################################################
# JOB 1
###################################################
jobs:

  prepare:

    runs-on: ubuntu-latest

    outputs:
      terraform_version: ${{ steps.output.outputs.tf_version }}

    steps:

      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set Output
        id: output
        run: |
          echo "tf_version=${TF_VERSION}" >> $GITHUB_OUTPUT

###################################################
# JOB 2
###################################################

  validate:

    needs: prepare

    runs-on: ubuntu-latest

    strategy:

      fail-fast: false

      matrix:

        environment:
          - dev
          - uat
          - prod

    environment:
      name: ${{ matrix.environment }}

    timeout-minutes: 30

    env:
      LOCATION: Central India

    steps:

      - uses: actions/checkout@v4

      - name: Setup Terraform

        uses: hashicorp/setup-terraform@v3

        with:
          terraform_version: ${{ needs.prepare.outputs.terraform_version }}

      - name: Azure Login

        uses: azure/login@v2

        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ vars.AZURE_SUBSCRIPTION }}

      - name: Terraform Init

        working-directory: ${{ env.WORKING_DIR }}

        run: terraform init

      - name: Terraform Format

        run: terraform fmt -check -recursive

      - name: Terraform Validate

        working-directory: ${{ env.WORKING_DIR }}

        run: terraform validate

      - name: Terraform Plan

        id: plan

        working-directory: ${{ env.WORKING_DIR }}

        run: |
          terraform plan \
          -var-file=${{ matrix.environment }}.tfvars \
          -out=tfplan

      - name: Upload Plan

        uses: actions/upload-artifact@v4

        with:

          name: tfplan-${{ matrix.environment }}

          path: terraform/tfplan

###################################################
# JOB 3
###################################################

  security:

    needs: validate

    runs-on: ubuntu-latest

    continue-on-error: false

    steps:

      - uses: actions/checkout@v4

      - name: Run TFLint

        uses: terraform-linters/setup-tflint@v4

      - run: tflint

      - name: Run tfsec

        uses: aquasecurity/tfsec-action@v1

      - name: Run Checkov

        uses: bridgecrewio/checkov-action@master

###################################################
# JOB 4
###################################################

  deploy:

    needs:
      - validate
      - security

    if: github.ref == 'refs/heads/main'

    runs-on: ubuntu-latest

    environment:
      name: production

    steps:

      - uses: actions/checkout@v4

      - name: Download Plan

        uses: actions/download-artifact@v4

        with:

          name: tfplan-prod

      - name: Setup Terraform

        uses: hashicorp/setup-terraform@v3

        with:
          terraform_version: ${{ env.TF_VERSION }}

      - name: Azure Login

        uses: azure/login@v2

        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ vars.AZURE_SUBSCRIPTION }}

      - name: Terraform Apply

        run: terraform apply tfplan
